### ISSUE TITLE
Refactor address form

### ISSUE THREAD

**Issue by ranzwertig** [all3dp/printing-engine-client#1131]
- Each address should have the firstName and lastName in its address section.
- Each address section should include a companyName

**Comment by Dansken** [comment]
@ranzwertig New design attached.

**Comment by Dansken** [comment]
![cc-address-modal](https://user-images.githubusercontent.com/25741371/60185032-7c6b5200-9829-11e9-91a6-bfaed139b341.jpg)

**Comment by Dansken** [comment]
![cc-address-modal-2](https://user-images.githubusercontent.com/25741371/60190144-7168ef80-9832-11e9-9e9e-3a0da88695c3.jpg)
![cc-address-modal-1](https://user-images.githubusercontent.com/25741371/60190145-7168ef80-9832-11e9-8e24-7f52956a9ee4.jpg)

**Comment by dreampulse** [comment]
```json
{
  "emailAddress": "user@example.com",
  "isCompany": true,
  "companyName": "string",
  "vatId": "string",
  "phoneNumber": "string",
  "useDifferentBillingAddress": true,
  "shippingAddress": {
    "firstName": "Max",
    "lastName": "Mustermann",
    "companyName": "Fooo", 
    "address": "Musterstraße 1",
    "city": "Musterstadt",
    "zip": "12345",
    "countryCode": "DE"
  },
  "billingAddress": {
    "firstName": "Max",
    "lastName": "Mustermann",
    "address": "Musterstraße 1",
    "city": "Musterstadt",
    "zip": "12345",
    "countryCode": "DE"
  }
}
```

**Comment by alex-all3dp** [comment]
Having another address line for the company name does not do us much good. We would rely on the printing providers do support a third address line (most don't). For all other cases we would start implementing workarounds in the backend, manipulating or concatenating the address lines manually.

What do we want to achieve? Ideally users use address line 1 for the company name + c/o and address line 2 for the address of the company. No additional fields are required to get all required information. We should look into simply improving our placeholders in the address form, rather than extending it with more optional fields.

Here is what amazon does, which looks good enough in my eyes and is probably thought through ;)

<img width="530" alt="Bildschirmfoto 2019-07-16 um 09 03 22" src="https://user-images.githubusercontent.com/52403795/61273339-88538f80-a7a9-11e9-847d-f7f4f84402b4.png">

**Comment by henry-all3dp** [comment]
Additionally to the proposed changes to the input form I would suggest to better display the generated shipping and billing addresses plus all the other entered information in the address form to the address header of the cart page:

```
Delivery Address                                   Billing Address
                                                   [Company Name] [VAT ID]
Firstname Lastname                                 Firstname Lastname
Address Line 1 (company, street)                   Address Line 1
[Address Line 2 (additional)]                      [Address Line 2]
[State] Zip City                                   [State] Zip City
Country                                            Country

Contact Email: emailAddress
Contact Phone: phoneNumber
```

**Comment by henry-all3dp** [comment]
Company name is still put inside the shipping address. This is something we did not want to display to the client to avoid confusion. Please fix display of address data as described in this ticket.

**Comment by henry-all3dp** [comment]
<img width="793" alt="grafik" src="https://user-images.githubusercontent.com/31536819/61956879-5074f500-afbe-11e9-80e8-a54325f7bf74.png">

**Comment by henry-all3dp** [comment]
<img width="560" alt="grafik" src="https://user-images.githubusercontent.com/31536819/61956906-5cf94d80-afbe-11e9-897d-7a2335edd444.png">
