### ISSUE TITLE
Implement traffic analytics - Use query parameters to understand the sources of where our users are coming from. [2sp]

### ISSUE THREAD

**Issue by Dansken** [all3dp/printing-engine-client#389]

**Comment by dreampulse** [comment]
Pass a query paramter to the order requests (utm-source)
Send parameter to mixpanel
Store the data next to the order
Send info to the slack channel
[2 storypoints]

**Comment by jhnns** [comment]
According to my research:

- [GA automatically detects the following `utm_` parameters](https://support.google.com/analytics/answer/1033863):


  - `utm_source`: Identify the advertiser, site, publication, etc. that is sending traffic to your property, for example: google, newsletter4, billboard.
  - `utm_medium`: The advertising or marketing medium, for example: cpc, banner, email newsletter.
  - `utm_campaign`: The individual campaign name, slogan, promo code, etc. for a product.
  - `utm_term`: Identify paid search keywords. If you're manually tagging paid keyword campaigns, you should also use utm_term to specify the keyword.
  - `utm_content`: Used to differentiate similar content, or links within the same ad. For example, if you have two call-to-action links within the same email message, you can use utm_content and set different values for each so you can tell which version is more effective.

- I coudln't confirm that the GA tracking SDK is extracting these parameters. It just sends the whole URL to `google-analytics.com` which makes sense because then they don't have to update the SDK when they change something. @Dansken needs to confirm that the `utm_` parameters are recognized

- Same goes for mixpanel. Acccording [to this site](https://mixpanel.com/help/questions/articles/can-i-track-google-analytics-style-utm-tags-with-mixpanel), the SDK automatically tracks the `utm_` parameters. I couldn't confirm that they are sending them to `mixpanel.com` but they are leaked through the `Referer` header, so that could be possible. @Dansken also needs to confirm that.

**Comment by Dansken** [comment]
@jhnns Please consult with @stefan-all3dp About this topic.

**Comment by stefan-all3dp** [comment]
Please, let us store all of the UTM-Parameters: utm_source, utm_medium, utm_campaign, utm_term, utm_content

**Comment by jhnns** [comment]
Should the utmParams be preserved when the configuration is shared?

**Comment by jhnns** [comment]
Blocked by https://github.com/all3dp/printing-engine/issues/411
