### ISSUE TITLE
MM: Define required API-Changes / Printing-Engine-API V3 [1 SP]

### ISSUE THREAD

**Issue by henry-all3dp** [all3dp/printing-engine-client#414]
Proposal for new API request flow:
![basket_checkout](https://user-images.githubusercontent.com/31536819/33425358-c5ce2c76-d5be-11e7-8030-b6bf844be55e.png)

Response payload for GET /shipping
```
shippings = {
  type: 'array',
  items: {
    title: 'Shipping',
    type: 'object',
    additionalProperties: false,
    required: ['vendorId', 'name', 'deliveryTime', 'price', 'currency'],
    properties: {
      vendorId: {type: 'string'},
      name: {type: 'string'},
      deliveryTime: {type: 'string'},
      price: {type: 'number'},
      currency: {type: 'string'}
    }
  }
}
```

Request payload for POST /price
```
priceRequest = {
  type: 'object',
  additionalProperties: false,
  required: ['currency', 'models', 'materialConfigIds'],
  properties: {
    currency: {type: 'string'},
    models: {
      type: 'array',
      items: {
        title: 'Model',
        type: 'object',
        required: ['id', 'quantity'],
        properties: {
          id: {type: 'string'},
          quantity: {type: 'number'}
        }
    },
    materialConfigIds: {
      type: 'array',
      items: {type: 'number'}
    }
  }
}
```

Response payload for POST /price 

```
{ 
  type: 'object', 
  properties: {
    priceId: 'string'
  }
}
```
Using the `priceId` you can poll for quotes as follows: 

Response payload for GET /price/:priceId
```
{ 
  type: 'object',
  properties: {
    printingServiceComplete: {
      type: 'object',
       properties: {
           imaterialize: { type: 'boolean' },
           sculpteo: { type: 'boolean' },
           shapeways: { type: 'boolean' }
       }
    },
    quotes: {
      type: 'array',
      items: {
        title: 'Quote',
        type: 'object',
        additionalProperties: false,
        required: ['quoteId', 'modelId', 'vendorId', 'materialConfigId', 'price', 'quantity', 'currency','isPrintable'],
    properties: {
      quoteId: {type: 'string'},
      vendorId: {type: 'string'},
      modelId: {type: 'string'},
      materialConfigId: {type: 'number'},
      price: {type: 'number'},
      quantity: {type: 'number'},
      currency: {type: 'string'},
      isPrintable: {type: 'boolean'}
    }
    }
  }
}
```

Request payload for POST /basket
```
basket = {
  type: 'object',
  additionalProperties: false,
  required: ['userId', 'quoteIds', 'shippingIds'],
  properties: {
    userId: {type: 'string'},
    quoteIds: {
      type: 'array',
      items: {type: 'string'}
    },
    shippingIds: {
      type: 'array',
      items: {type: 'string'}
    }
  }
}
```

**Comment by tanx** [comment]
Looks good as far as I can tell. @webholics @dreampulse any feedback from your side?

**Comment by webholics** [comment]
Looks good to me. 
Two minor things I just expect to be true:

- We can load user and materials concurrently. But shipping only after the user has been created (because of the location).
- A post to the basket will validate if there are quotes which cannot be shipped with the provided shippingIds or vice-versa.

**Comment by jhnns** [comment]
I have some minor questions:

- The `GET /shipping` request requires a country code, like `GET /shipping/:countryCode`

> We can load user and materials concurrently. But shipping only after the user has been created (because of the location).

If the user is new, we can do the `/POST user` and the `GET /shipping/:countryCode` request in parallel. Are there situations where the user is already known? Maybe we can persist the user in the `sessionStorage` so that new orders don't require the user to re-enter all the details.

- What happened to the polling API? Is it still there? And if yes, I think it would be better if `POST /price` would return a URL where the quotes will appear once they are ready (maybe under `GET /quotes/:id`?)
- In general, the new API should provide all status information in the response body. For instance, the current price API returns a non-200 status code when some quotes are still pending. In my experience, expressing this kind of application state entirely via HTTP status codes can be problematic because HTTP status code are not granular enough. Imho it's better to provide an explicit application state in the response + the corresponding HTTP status code.
- What if the quote response contains an array with the all quotes for all requested material config ids. Each quote has a `state` which can either be `"PENDING"`, `"PRINTABLE"` or `"NOT_PRINTABLE"`. Depending on the `state` the quote may have different properties (like `price`) (Flow calls this kind of type a [disjoint union type](https://flow.org/en/docs/types/unions/#toc-disjoint-unions)). I think, this kind of switch makes it easier to handle it in the frontend. The schema definition is also cleaner because this way the response does not contain invalid properties (if a quote is not printable, why does it have a `price` property?).
- Why do we need a user id when creating a price request?

**Comment by dreampulse** [comment]
I think new api design is very good. In addition to the point above:

> In general, the new API should provide all status information in the response body. For instance, the current price API returns a non-200 status code when some quotes are still pending. In my experience, expressing this kind of application state entirely via HTTP status codes can be problematic because HTTP status code are not granular enough. Imho it's better to provide an explicit application state in the response + the corresponding HTTP status code.

I agree to that. I would be helpful to have a field like: `isComplete` for the polling API.

**Comment by jhnns** [comment]
@tanx @henry-all3dp what do you think?

**Comment by henry-all3dp** [comment]
Just get started and when you discover the need for more attributes we can always add them without breaking the API.

**Comment by meaku** [comment]
Resolved comments by @webholics and @jhnns. We added notes inline.
