### ISSUE TITLE
Bug: Paypal is no longer working. Loads and disappears.

### ISSUE THREAD

**Issue by Dansken** [all3dp/printing-engine-client#508]

**Comment by henry-all3dp** [comment]
@tanx what do you think of adding dotenv (https://github.com/motdotla/dotenv) respectively dotenv-safe (https://github.com/rolodato/dotenv-safe) to the printing-engine as suggested by @jhnns to prevent such errors (i.e. missing env params).

I did a quick implementation but found that due to our current setup with node-config (https://github.com/lorenwest/node-config) it is not easy for us to dynamically override config values with environmental variables provided by dotenv. I could not find a working solution, though.

What do you think about a solution like this for the problem? Shall we completely spare test for env param existence, use a node module like dotenv-safe or do you think for some critical parameters we should do this manually?
